<?php

function extra_modes_entity_info_alter(&$entity_info){
    $entity_info['node']['view modes']['feature_card'] = array(
        'label' => t('Feature Card'),
        'custom settings' => TRUE,
    );
    $entity_info['node']['view modes']['bibs_now'] = array(
        'label' => t('BIBS now'),
        'custom settings' => TRUE,
    );
    $entity_info['node']['view modes']['under_card'] = array(
        'label' => t('Undergrad Card'),
        'custom settings' => TRUE,
    );
}
